"use client";
import { useEffect, useState } from "react";
import { IoArrowBackOutline } from "react-icons/io5";
import { toaster } from "@/utils";

type Session={_id:string;device:string;ip:string;userAgent:string;createdAt:string;lastActiveAt:string;isCurrent?:boolean};
export default function SecuritySettings({getBack}:{getBack:()=>void}){
 const [sessions,setSessions]=useState<Session[]>([]);const [twoFactor,setTwoFactor]=useState(false);const [secret,setSecret]=useState("");const [codes,setCodes]=useState<string[]>([]);const [token,setToken]=useState("");const [loading,setLoading]=useState(false);
 const load=async()=>{const [s,t]=await Promise.all([fetch("/api/auth/sessions"),fetch("/api/auth/2fa",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"status"})})]);if(s.ok)setSessions((await s.json()).sessions||[]);if(t.ok)setTwoFactor(Boolean((await t.json()).enabled));};
 useEffect(()=>{load()},[]);
 const setup=async()=>{setLoading(true);try{const r=await fetch("/api/auth/2fa",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"setup"})});const d=await r.json();if(!r.ok)throw new Error(d.message);setSecret(d.secret);setCodes(d.backupCodes||[])}catch(e){toaster("error",e instanceof Error?e.message:"2FA setup failed")}finally{setLoading(false)}};
 const enable=async()=>{const r=await fetch("/api/auth/2fa",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"enable",token})});const d=await r.json();if(!r.ok)return toaster("error",d.message||"Invalid code");setTwoFactor(true);setSecret("");setCodes([]);setToken("");toaster("success","Two-factor authentication enabled")};
 const terminate=async(id?:string)=>{const r=await fetch("/api/auth/sessions",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify(id?{sessionId:id}:{all:true})});if(r.ok){const data=await r.json().catch(()=>({}));if(id&&sessions.find(s=>s._id===id)?.isCurrent){window.location.href="/";return;}await load();toaster("success","Session terminated")}else{const data=await r.json().catch(()=>({}));toaster("error",data.message||"Failed to terminate session")}};
 return <div className="min-h-dvh text-white p-4"><button onClick={getBack} className="flex items-center gap-2 mb-5"><IoArrowBackOutline/>Security</button>
 <section className="mb-8"><h3 className="font-bold mb-3">Two-factor authentication</h3>{twoFactor?<div className="flex gap-2"><input value={token} onChange={e=>setToken(e.target.value)} placeholder="6-digit code" className="bg-white/10 rounded p-2"/><button onClick={async()=>{const r=await fetch("/api/auth/2fa",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"disable",token})});if(r.ok){setTwoFactor(false);setToken("");toaster("success","2FA disabled")}else toaster("error","Invalid code")}} className="bg-red-600 rounded px-3">Disable</button></div>:secret?<div className="space-y-3"><p className="text-sm break-all">Secret: {secret}</p><p className="text-xs text-white/60">Save these backup codes somewhere safe:</p><pre className="bg-black/30 p-3 rounded text-xs">{codes.join("\n")}</pre><div className="flex gap-2"><input value={token} onChange={e=>setToken(e.target.value)} placeholder="6-digit authenticator code" className="bg-white/10 rounded p-2"/><button disabled={loading} onClick={enable} className="bg-lightBlue rounded px-3">Enable</button></div></div>:<button onClick={setup} className="bg-lightBlue rounded px-3 py-2">Set up TOTP</button>}</section>
 <section><div className="flex justify-between items-center mb-3"><h3 className="font-bold">Active sessions</h3><button onClick={()=>terminate()} className="text-red-400 text-sm">Terminate all</button></div>{sessions.map(s=><div key={s._id} className="border-b border-white/10 py-3 flex justify-between gap-3"><div className="min-w-0"><div>{s.device}{s.isCurrent ? " · Current" : ""}</div><div className="text-xs text-white/50 truncate">{s.ip} · {s.userAgent}</div><div className="text-xs text-white/40">{new Date(s.lastActiveAt).toLocaleString()}</div></div><button onClick={()=>terminate(s._id)} className="text-red-400 text-sm">Terminate</button></div>)}</section></div>;
}
